POST https://appix-ai-designs.azurewebsites.net/api/ProxyFunction?url=https://aiavatar.innovationcatalog.pwc.com/ai-avatar/api/v1/auth/login
Content-Type: application/json

{
  "username": "ivan",
  "password": "ivan"
}

###
POST https://appix-ai-designs.azurewebsites.net/api/ProxyFunction?url=https%3A%2F%2Faiavatar.innovationcatalog.pwc.com%2Fai-avatar%2Fapi%2Fv1%2Fauth%2Flogin
Content-Type: application/json

{
  "username": "ivan",
  "password": "ivan"
}


###
GET https://appix-ai-designs.azurewebsites.net/api/Ping