@theHostname = https://appix-ai-designs.azurewebsites.net/api
#@theHostname = http://localhost:7071/api

### Get config for an application
GET {{theHostname}}/config/pickleball-ios

### Get config for another application
GET {{theHostname}}/config/anotherApp

