# @theHostname = https://appix-ai-designs.azurewebsites.net/api
@theHostname = http://localhost:7071/api
@theItem = merch

### Merch Get All
GET {{theHostname}}/{{theItem}}

### Merch Get By Id
GET {{theHostname}}/{{theItem}}/1

### Merch Get By Product Id
GET {{theHostname}}/{{theItem}}/product/1

### Merch Get By Category Id
GET {{theHostname}}/{{theItem}}/category/1

### Merch Filter
GET {{theHostname}}/{{theItem}}/filter?categoryIds=1&productId=1&isMine=true&isTopCategory=true&isNewCategory=true

### Merch Filter
GET {{theHostname}}/merch/filter?categoryIds=4